const supportedCountries = [
  {
    country: "United Kingdom",
    country_code: "GB",
    currency: "British Pound Sterling",
    currency_code: "GBP",
    symbol: "£",
    continent: "Europe",
  },
  {
    country: "Canada",
    country_code: "CA",
    currency: "Canadian Dollar",
    currency_code: "CAD",
    symbol: "$",
    continent: "North America",
  },
  {
    country: "Cameroon",
    country_code: "CM",
    currency: "Central African CFA Franc",
    currency_code: "XAF",
    symbol: "FCFA",
    continent: "Africa",
  },
  {
    country: "Central African Republic",
    country_code: "CF",
    currency: "Central African CFA Franc",
    currency_code: "XAF",
    symbol: "FCFA",
    continent: "Africa",
  },
  {
    country: "Chad",
    country_code: "TD",
    currency: "Central African CFA Franc",
    currency_code: "XAF",
    symbol: "FCFA",
    continent: "Africa",
  },
  {
    country: "Republic of the Congo",
    country_code: "CG",
    currency: "Central African CFA Franc",
    currency_code: "XAF",
    symbol: "FCFA",
    continent: "Africa",
  },
  {
    country: "Equatorial Guinea",
    country_code: "GQ",
    currency: "Central African CFA Franc",
    currency_code: "XAF",
    symbol: "FCFA",
    continent: "Africa",
  },
  {
    country: "Gabon",
    country_code: "GA",
    currency: "Central African CFA Franc",
    currency_code: "XAF",
    symbol: "FCFA",
    continent: "Africa",
  },
  {
    country: "Chile",
    country_code: "CL",
    currency: "Chilean Peso",
    currency_code: "CLP",
    symbol: "$",
    continent: "South America",
  },
  {
    country: "Colombia",
    country_code: "CO",
    currency: "Colombian Peso",
    currency_code: "COP",
    symbol: "$",
    continent: "South America",
  },
  {
    country: "Egypt",
    country_code: "EG",
    currency: "Egyptian Pound",
    currency_code: "EGP",
    symbol: "£",
    continent: "Africa",
  },
  {
    country: "Austria",
    country_code: "AT",
    currency: "Euro",
    currency_code: "EUR",
    symbol: "€",
    continent: "Europe",
  },
  {
    country: "Belgium",
    country_code: "BE",
    currency: "Euro",
    currency_code: "EUR",
    symbol: "€",
    continent: "Europe",
  },
  {
    country: "France",
    country_code: "FR",
    currency: "Euro",
    currency_code: "EUR",
    symbol: "€",
    continent: "Europe",
  },
  {
    country: "Germany",
    country_code: "DE",
    currency: "Euro",
    currency_code: "EUR",
    symbol: "€",
    continent: "Europe",
  },
  {
    country: "Ireland",
    country_code: "IE",
    currency: "Euro",
    currency_code: "EUR",
    symbol: "€",
    continent: "Europe",
  },
  {
    country: "Italy",
    country_code: "IT",
    currency: "Euro",
    currency_code: "EUR",
    symbol: "€",
    continent: "Europe",
  },
  {
    country: "Netherlands",
    country_code: "NL",
    currency: "Euro",
    currency_code: "EUR",
    symbol: "€",
    continent: "Europe",
  },
  {
    country: "Portugal",
    country_code: "PT",
    currency: "Euro",
    currency_code: "EUR",
    symbol: "€",
    continent: "Europe",
  },
  {
    country: "Spain",
    country_code: "ES",
    currency: "Euro",
    currency_code: "EUR",
    symbol: "€",
    continent: "Europe",
  },
  {
    country: "Ghana",
    country_code: "GH",
    currency: "Ghanaian Cedi",
    currency_code: "GHS",
    symbol: "₵",
    continent: "Africa",
  },
  {
    country: "Guinea",
    country_code: "GN",
    currency: "Guinean Franc",
    currency_code: "GNF",
    symbol: "FG",
    continent: "Africa",
  },
  {
    country: "Kenya",
    country_code: "KE",
    currency: "Kenyan Shilling",
    currency_code: "KES",
    symbol: "KSh",
    continent: "Africa",
  },
  {
    country: "Malawi",
    country_code: "MW",
    currency: "Malawian Kwacha",
    currency_code: "MWK",
    symbol: "MK",
    continent: "Africa",
  },
  {
    country: "Morocco",
    country_code: "MA",
    currency: "Moroccan Dirham",
    currency_code: "MAD",
    symbol: "د.م.",
    continent: "Africa",
  },
  {
    country: "Nigeria",
    country_code: "NG",
    currency: "Nigerian Naira",
    currency_code: "NGN",
    symbol: "₦",
    continent: "Africa",
  },
  {
    country: "Rwanda",
    country_code: "RW",
    currency: "Rwandan Franc",
    currency_code: "RWF",
    symbol: "FRw",
    continent: "Africa",
  },
  {
    country: "Sierra Leone",
    country_code: "SL",
    currency: "Sierra Leonean Leone",
    currency_code: "SLL",
    symbol: "Le",
    continent: "Africa",
  },
  {
    country: "São Tomé and Príncipe",
    country_code: "ST",
    currency: "São Tomé and Príncipe Dobra",
    currency_code: "STD",
    symbol: "Db",
    continent: "Africa",
  },
  {
    country: "South Africa",
    country_code: "ZA",
    currency: "South African Rand",
    currency_code: "ZAR",
    symbol: "R",
    continent: "Africa",
  },
  {
    country: "Tanzania",
    country_code: "TZ",
    currency: "Tanzanian Shilling",
    currency_code: "TZS",
    symbol: "TSh",
    continent: "Africa",
  },
  {
    country: "Uganda",
    country_code: "UG",
    currency: "Ugandan Shilling",
    currency_code: "UGX",
    symbol: "USh",
    continent: "Africa",
  },
  {
    country: "United States",
    country_code: "US",
    currency: "United States Dollar",
    currency_code: "USD",
    symbol: "$",
    continent: "North America",
  },
  {
    country: "Benin",
    country_code: "BJ",
    currency: "West African CFA Franc BCEAO",
    currency_code: "XOF",
    symbol: "CFA",
    continent: "Africa",
  },
  {
    country: "Burkina Faso",
    country_code: "BF",
    currency: "West African CFA Franc BCEAO",
    currency_code: "XOF",
    symbol: "CFA",
    continent: "Africa",
  },
  {
    country: "Côte d’Ivoire",
    country_code: "CI",
    currency: "West African CFA Franc BCEAO",
    currency_code: "XOF",
    symbol: "CFA",
    continent: "Africa",
  },
  {
    country: "Guinea-Bissau",
    country_code: "GW",
    currency: "West African CFA Franc BCEAO",
    currency_code: "XOF",
    symbol: "CFA",
    continent: "Africa",
  },
  {
    country: "Mali",
    country_code: "ML",
    currency: "West African CFA Franc BCEAO",
    currency_code: "XOF",
    symbol: "CFA",
    continent: "Africa",
  },
  {
    country: "Niger",
    country_code: "NE",
    currency: "West African CFA Franc BCEAO",
    currency_code: "XOF",
    symbol: "CFA",
    continent: "Africa",
  },
  {
    country: "Senegal",
    country_code: "SN",
    currency: "West African CFA Franc BCEAO",
    currency_code: "XOF",
    symbol: "CFA",
    continent: "Africa",
  },
  {
    country: "Togo",
    country_code: "TG",
    currency: "West African CFA Franc BCEAO",
    currency_code: "XOF",
    symbol: "CFA",
    continent: "Africa",
  },
  {
    country: "Zambia",
    country_code: "ZM",
    currency: "Zambian Kwacha",
    currency_code: "ZMW",
    symbol: "ZK",
    continent: "Africa",
  },
];

// Get country info by filter (e.g., country name or country code)
function getSupportedCountry(filter) {
  if (!filter || typeof filter !== "object") {
    throw new Error("Filter must be an object, e.g. { country: 'Nigeria' }");
  }

  const [key, value] = Object.entries(filter)[0];

  const result = supportedCountries.find(
    (item) =>
      item[key] &&
      item[key].toString().toLowerCase() === value.toString().toLowerCase()
  );

  return result || null;
}

module.exports = { getSupportedCountry, supportedCountries };
